source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SNMediator_Example' do
  pod 'SNMediator', :path => '../'

  target 'SNMediator_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
end
